'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PostedDataDeletion

    '''<summary>
    '''mvposteddatadeletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvposteddatadeletion As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''PostedDataDeletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostedDataDeletion As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPDDClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDDClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPDDClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPDDClient As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rbPDDLockbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDDLockbox As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPDDEFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDDEFT As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPDDCreditCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDDCreditCard As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPDDOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDDOther As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''postedData_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postedData_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkPDDGridSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPDDGridSelectAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPDDCurrentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDDCurrentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDDsearchBatchId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDsearchBatchId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDsearchInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDsearchInvoice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDsearchCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDsearchCheck As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDsearchClosingDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDsearchClosingDt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDsearchDepositDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDsearchDepositDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDSearchCreateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDSearchCreateDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDsearchDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDsearchDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDSearchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDSearchType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPDDsearchPayamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPDDsearchPayamt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDSearchPayCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDSearchPayCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDDSearchPosteddt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDDSearchPosteddt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''div_PDDLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_PDDLoad As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdPostedDataDeletionLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPostedDataDeletionLoad As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lnkPDDdelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPDDdelete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkPDDReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPDDReturn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hfCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCount As Global.System.Web.UI.WebControls.HiddenField
End Class
