'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PostedDataCorrection

    '''<summary>
    '''mvposteddatacorrection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvposteddatacorrection As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''PostedDataLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostedDataLoad As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPDCClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDCClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPDCClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPDCClient As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rbPDCLockbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDCLockbox As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPDCEFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDCEFT As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPDCCreditCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDCCreditCard As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPDCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPDCOther As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''postedData_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postedData_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkPDCGridSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPDCGridSelectAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPDCType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDCType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPDCCurrentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDCCurrentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDCsearchBatchId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCsearchBatchId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCsearchInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCsearchInvoice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCsearchCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCsearchCheck As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCsearchClosingDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCsearchClosingDt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCsearchDepositDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCsearchDepositDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCSearchCreateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCSearchCreateDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCsearchDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCsearchDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCSearchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCSearchType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPDCsearchPayamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPDCsearchPayamt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCSearchPayCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCSearchPayCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCSearchcomment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCSearchcomment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDCSearchPosteddt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDCSearchPosteddt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''div_PDCLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_PDCLoad As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdPostedDataCorrectionLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPostedDataCorrectionLoad As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lnkPDCPush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPDCPush As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkPDCdelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPDCdelete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkPDCReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPDCReturn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hfPDCDeleteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPDCDeleteCount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPDCPushCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPDCPushCount As Global.System.Web.UI.WebControls.HiddenField
End Class
