'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WorkQueueOther

    '''<summary>
    '''lnkWQQueueTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkWQQueueTotals As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkWQSelectedQueue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkWQSelectedQueue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblWQClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWQClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWQSelectedQueue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWQSelectedQueue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkNewBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewBank As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPartiallymatched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartiallymatched As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Mat_Sea_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mat_Sea_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MatNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MatNum As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''mckh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mckh As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtBankDataSearchCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankDataSearchCheck As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBankDataSearchDepositDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankDataSearchDepositDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBankDataSearchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankDataSearchType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtBankDataSearchPayamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBankDataSearchPayamt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Mat_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mat_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdBankData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdBankData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblBankDataCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBankDataCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPostedData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostedData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRefresh As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Unmat_Sea_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Unmat_Sea_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PostedDataNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostedDataNum As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ckh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckh As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TxtPostedDataNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataBatchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataBatchID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataInv As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataChk As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataBDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataBDD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataCD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataCDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataCDt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataDes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDaTaPayAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDaTaPayAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataPayCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataPayCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostedDataPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostedDataPD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Unmat_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Unmat_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grdPostedData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPostedData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblPostedDatacount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostedDatacount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUpdate As Global.System.Web.UI.WebControls.LinkButton
End Class
